version: '3'

services:
  mysql:
    image: mysql:8.0
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shin_on_wiki
      MYSQL_USER: bookstack
      MYSQL_PASSWORD: bookstack
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
    driver: local
