<?php

/**
 * Portal JWT authentication configuration options.
 *
 * Used when AUTH_METHOD=portal_jwt to authenticate via shin-on_portal's
 * portal_jwt cookie (RS256 signed JWT).
 *
 * Changes to these config files are not supported by BookStack and may break upon updates.
 * Configuration should be altered via the `.env` file or environment variables.
 * Do not edit this file unless you're happy to maintain any changes yourself.
 */

return [

    // JWKS endpoint URL for portal public key retrieval
    'jwks_url' => env('PORTAL_JWKS_URL', 'https://portal.shin-on1981.com/api/jwks/'),

    // Expected JWT issuer (iss claim)
    'issuer' => env('PORTAL_JWT_ISSUER', 'https://portal.shin-on1981.com'),

    // Expected JWT audience (aud claim)
    'audience' => env('PORTAL_JWT_AUDIENCE', 'wiki'),

    // Portal login URL (users are redirected here when unauthenticated)
    'login_url' => env('PORTAL_LOGIN_URL', 'https://portal.shin-on1981.com/login/'),

    // Portal logout URL (users are redirected here on logout)
    'logout_url' => env('PORTAL_LOGOUT_URL', 'https://portal.shin-on1981.com/logout/'),

    // Cookie name used by the portal
    'cookie_name' => env('PORTAL_JWT_COOKIE', 'portal_jwt'),

    // JWKS cache TTL in seconds
    'jwks_cache_ttl' => 3600,

];
